### PR TITLE
Add formatter option to asDate()

### LINKED ISSUE #113: Add formatter option to asDate()
Sometimes you need transformed date object. Timestamp, ISOString, etc.
Propose adding the option.

### PR DESCRIPTION
**Pull request by immitsu**
Resolves #113

### CODE REVIEW

**Comment by jcteague** [comment]
@immitsu Thank you for the PR!.  

I have some concerns about the formatter function.  The date builder needs to return a valid date object, and not all methods on the Date object returns dates.  You're test is actually an example, where you're using `getMonth` would just be an integer value and not an actual date.

What are some of the use cases you're thinking of?  Perhaps we can find an alternative approach.

**Comment by immitsu** [comment]
@jcteague Thank you for the lib!

For example, I want to represent a date as timestamp or ISO.
In fact, this can be done right now using the `as` generator to provide custom function.

If it was so intended, that the date builder returns only date object - then mr should be closed.

I realized what could confuse me. The project documentation has section called [provided-type-generators](https://github.com/jcteague/efate#provided-type-generators), where some methods are actually about generating formal types (e.g. `asDate` and `asNumber`) and others are about generating values (e.g. `asEmail` and `asFirstName`). It may be worth distinguishing methods more clearly in the future.

**Comment by jcteague** [comment]
I see, you'd like to have a `string` field be populated by a date formatted as timestamp or ISO.

Probably the best way to do this would be with an [extension](https://github.com/jcteague/efate#extensions).  That way you use something like the date-fns library.  I've been trying to keep external libraries to a minimum, so I've been creating extensions that use other libraries instead of adding them to the core library (but I'm probably being too inflexible on that).

I could see creating an extension with a `asISODateString()` function or `asFormattedDateString({format})` function signature being very useful.

The `asEmail` and `asFirstName` were attempts of doing some common formats to make it easier.  But now that there is the faker extension, these are probably irrelevant.  

Any recommendations to make the documentation better is greatly appreciated!

**Comment by jcteague** [comment]
Closing, suggestions made above

**Pull request closed without merging**
